@startuml
class main
main : main();




class bestillinger
bestillinger : orders : int[4][4];
bestillinger : orderChanged : int = 1;

bestillinger : ordersEmpty() : int;
bestillinger : clearOrderRow(row : int);
bestillinger : settBestillinger();



class heis
heis : heading : int = 1;
heis : doorOpen : int = 1;
heis : lastFloor : int = 1;

heis : settHeading(etg : int);
heis : bevegelse();
heis : stopInFloor(etg : int);
heis : openDoor();
heis : closeDoor();
heis : waitDoor();



class panel
panel : floorLights(); 
panel : panelLights();
panel : obstruksjon();
panel : stoppKnapp();


class elvio
elvio : elvio_init();
elvio : elevio_motorDirection(dirn : MotorDirection);
elvio : elevio_floorSensor(); : int
elvio : elevio_buttonLamp();
elvio : elevio_obstruction(); : int
elvio : elvio_stopLamp(value : int);
elvio : elbvio_stopButton();



main --> heis
main --> elvio
main --> panel
main --> bestillinger

heis --> bestillinger
heis --> elvio

bestillinger -> elvio

panel --> elvio





note right of main
    oppstart & logikk syklus
end note
@enduml
